[tool.poetry]
name = "hello-ray"
version = "0.1.0"
description = ""
authors = ["Anthony Naddeo <anthony@whylabs.ai>"]

[tool.poetry.dependencies]
python = "3.8"
ray = {extras = ["default"], version = "^1.6.0"}
whylogs = "^0.6.7"
pyarrow = "^5.0.0"
fsspec = "^2021.10.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
